### ISSUE TITLE
Using active_record and Mongoid together but get nil

### ISSUE THREAD

**Issue by confact** [davidcelis/recommendable#104]
Running active_record for the recommendable and mongoid for something else in same rails app.
recommendable is not touching mongoid and should not worry about it. I get ```Your ORM is not currently supported. Please open an issue at https://github.com/davidcelis/recommendable``` but i ignore that because i don't use mongoid for the models and controllers recommendable will use.

Seems to not work anyway because i get ```undefined method `limit' for nil:NilClass```
and the line is:
```
if current_user.recommended_stations.limit(25).size > 0
```

The model user have this stuff:
```
class User < ActiveRecord::Base
has_merit

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include RailsAdminCharts
  include PublicActivity::Model
  extend FriendlyId
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :authentication_keys => [:login]
  acts_as_followable
  acts_as_follower
  acts_as_commontator
  friendly_id :username, :use => :slugged
  subscribe_me_using :email, :name => :name, :added => :created_at
  recommends :stations
....
````
Is this a bug or am i doing something wrong?

**Comment by confact** [comment]
Okay, i forked and started to debug it. it said mongoid as orm in recommendable's config even when i use active_record in this parts. So i set ```config.orm = 'active_record'``` in recommendable initializer and that made the trick.

I save this here @davidcelis so you maybe can see and add this notice to readme.

**Comment by davidcelis** [comment]
Added; thank you!
