### ISSUE TITLE
Object has not been declared ratable.

### ISSUE THREAD

**Issue by confact** [davidcelis/recommendable#105]
Having issue liking a object.
getting ```Object has not been declared ratable.``` when doing this:

```
current_user.like(station)
```

I have recommends: :stations in User so this should work, accordingly to the documentation.

What am i doing wrong?

**Comment by davidcelis** [comment]
Are you sure that station is an instance of `Station`? Does `Recommendable.config.ratable_classes` return anything?

**Comment by confact** [comment]
@davidcelis Yea, I had issues with id which worked on one place but not another and yea, made me confused. The problem was that the id param was nil, so station wasn't found.

Sorry about that, closing this.
