### ISSUE TITLE
User recommendation

### ISSUE THREAD

**Issue by mbajur** [davidcelis/recommendable#110]
Hey! Please, tell me, is that possible to create a "People you may know" functionality using recommendable gem?

I decided to give it a try by using `like` as a `following` relation. Here is my environment:

![image](https://cloud.githubusercontent.com/assets/581569/8581084/c22caa14-25be-11e5-8683-fef3ec1787a7.png)

* B follows C
* D follows C
* D follows M

#### What i'm trying to achieve

* When user A follows user B, he should receive only C as a suggestion
* When user A follows user B and D, he should receive C and E as a suggestions

### What i'm currently doing

    # B follows C
    user_b.like(user_c)

    # D follows C
    user_d.like(user_c)

    # D follows E
    user_d.like(user_e)

    # The below does not behave as i want it to - there are no any suggestions 
    # for user A after that.
    #
    # A follows B and D
    user_a.like(user_b)
    user_a.like(user_d)

What's wrong in here? I feel a bit lost in all that recommendation thing (that's probably third gem/tool i'm trying to use for that functionality and i'm still not able to do anything). Thanks in advance :)

**Comment by davidcelis** [comment]
Hi, @mbajur! Thanks for trying out my little gem. Recommendable should work really well for your usecase, and it seems like you already figured out how to do that. Using `likes` in replacement of `follows` is exactly what I would do too, and it should work great that way. My guess is that you aren't running a background processor like Sidekiq or Resque and also aren't manually updating your recommendation data. Recommendable ships with background workers for common processors like Sidekiq, Resque, and DelayedJob. If one of those processes is running actively, it _should_ just work and refresh recommendations when a user submits a new like.

If you're just playing around locally, you can update your recommendation data like this:

```
User.all.each do |user|
  Recommendable::Helpers::Calculations.update_similarities_for(user.id)
  Recommendable::Helpers::Calculations.update_recommendations_for(user.id)
end
```

Could you try that and then let me know if user_a gets any suggestions?

**Comment by mbajur** [comment]
I have removed that code few minutes ago but i'm gonna recreate it tomorrow and let you know if that helped. Anyway - i have a recommendable sidekiq queue and i can see that there are some workers running when i'm *liking* stuff - is that enough?

**Comment by davidcelis** [comment]
That should be enough, yeah.  I'd still suggest running that above code manually just in case and let me know if that doesn't help.

**Comment by mbajur** [comment]
Ok i decided to recreate it now. I have run that code you provided and the output is the same with and without it - the only recommendation i can get in given environment when user A likes ONLY user B is that `user_b.recommended_users` returns **user_E** as a recommendation. Running `recommended_users` on any other user (including A) returns `[]`

**Comment by davidcelis** [comment]
Oh actually, that makes sense. Sorry, I misunderstood the original situation. Recommendable doesn't really do the sort of recommendation logic you're talking about, it's all collaborative filtering. So it makes sense that the only recommendation is User E being recommended to User B. The reason for that is that both User B and User D follow User C. That increases the similarity between User B and User D, so User D's _other_ like (User E) is recommended to User B. Does that make sense?

**Comment by mbajur** [comment]
yeah, that totally makes sense :) too bad such scenario is not supported. I'm gonna continue my search for such thing. Big thanks for your help! :)
