### ISSUE TITLE
blog post in project description is 404

### ISSUE THREAD

**Issue by jm3** [davidcelis/recommendable#114]
:o

**Comment by davidcelis** [comment]
@jm3 Hmmm.. Which blog post? The only one I see linked is to http://davidcelis.com/blog/2012/02/07/collaborative-filtering-with-likes-and-dislikes/ but that correctly redirects to https://davidcel.is/posts/collaborative-filtering-with-likes-and-dislikes/ when I click on it… Any more info for me? 😰

**Comment by jm3** [comment]
project desc: :+1::-1: A recommendation engine using Likes and Dislikes for your Ruby app http://davidcel.is/recommendable

clicking that goes to a 404 for me in chrome (AWS error)

**Comment by davidcelis** [comment]
Oh nice, my custom 404 page doesn't show up. That's :cool:. I'll figure out what's going on with both that and the missing page. Thanks!

**Comment by jm3** [comment]
👍
