### ISSUE TITLE
user.recommended_things always return empty

### ISSUE THREAD

**Issue by shaam48** [davidcelis/recommendable#120]
@davidcelis So when I have multiple users liking a particular instance of another model, I still can't get the recommended_thing and similar_raters methods to return anything; they are always empty. The like/dislike methods are working well though. I've played around with config/initializers/recommendable.rb (what it looks like right now):

```
require 'redis'

Recommendable.configure do |config|
  config.redis_namespace = :recommendable
  config.auto_enqueue = true
  config.nearest_neighbors = 5
  # config.furthest_neighbors = nil
  config.recommendations_to_store = 5
end

```

I'm using sidekiq with redis.

**Comment by shaam48** [comment]
I've changed my config/initializers/recommendable.rb:
```
require 'redis'

Recommendable.configure do |config|
  config.redis = Redis.new(:host => 'localhost', :port => 6379, :db => 0)
  config.redis_namespace = :recommendable
  config.auto_enqueue = true
  config.queue_name = :recommendable
  config.nearest_neighbors = nil
end
```

Sidekiq then generates the following error:
```
NoMethodError: undefined method `count' for nil:NilClass
```

**Comment by shaam48** [comment]
Issue solved as I added `config.user_class = User` to config/initializers/recommendable.rb

**Comment by phensalves** [comment]
@shaam48 same issue here, even after added config.user_class = User... =(

**Comment by truongnmt** [comment]
I added `config.user_class = User` but it's not work!

**Comment by truongnmt** [comment]
@phensalves have you able to make it work
