### ISSUE TITLE
Recommend model in module/engine

### ISSUE THREAD

**Issue by jbfeldis** [davidcelis/recommendable#53]
Hello David,

I'm having some trouble using recommendable with models in Forem (Forem::Post for example).

I can't just do `recommends :post` as no one knows that model and doing `recommends "Forem::Post"` works but then I don't have access to dynamic methods like `liked_`.

Any idea how to manage that would be welcome!

Thanks

**Comment by davidcelis** [comment]
I got another request for this via email today, so I'm just going to remove the privacy settings from those methods (it basically doesn't matter in Ruby anyway) and release a new patch version.
