### ISSUE TITLE
date when something was liked

### ISSUE THREAD

**Issue by mariobischof** [davidcelis/recommendable#94]
hi there. this is not a bug/nor a feature request (maybe it is), but is there any way to get the date when someone liked or bookmarked an object with recommendable? I want to implement something like a history. I appreciate any suggestions.

**Comment by samstarling** [comment]
Hi @davidcelis - just as a small follow up to this, I assume that for this same reason, it's not possible to get the most recent _n_ likes from (for example) `liked_products`?

**Comment by davidcelis** [comment]
@samstarling That's right; there's no ordering of items in a redis set, so you'd have to keep track of that sort of event on your own

**Comment by samstarling** [comment]
@davidcelis Thanks, that's really useful to know.
